/data_collecting_actuation_cmd:
  ros__parameters:
    # params for data_collecting_actuation_cmd
    TARGET_VELOCITY: 11.80
    TARGET_ACTUATION_FOR_ACCEL: 0.3
    TARGET_ACTUATION_FOR_BRAKE: 0.5
    TARGET_JERK_FOR_DRIVE: 1.5
    TARGET_JERK_FOR_BRAKE: -1.5
    MAX_ACCEL_PEDAL: 0.5
    MIN_BRAKE_PEDAL: 0.8
    topics:
      - /vehicle/status/velocity_status
      - /control/command/control_cmd
      - /sensing/imu/imu_data
      - /vehicle/status/control_mode
    validation_nodes:
      - /raw_vehicle_cmd_converter
      - /data_collecting_pure_pursuit_trajectory_follower_actuation_cmd
